In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
xls = pd.ExcelFile('CryptoGrams.xlsx')
xls.sheet_names

['Vigenere', 'SS']

In [3]:
ss = pd.read_excel(xls, "SS", header=None, names=["cipher"])
vig = pd.read_excel(xls, "Vigenere", header=None, names=["cipher"])

# Train Data Preprocessing

In [4]:
df = pd.concat([ss, vig])

In [5]:
y =  [0]*50 + [1]*50

In [20]:
ss_train = pd.concat([ss, vig])

In [21]:
vig_train = pd.concat([vig, ss])

In [22]:
y_ss = [0]*50 + [1]*50
y_vig = [1]*50 + [0]*50

# Model

In [6]:
v = TfidfVectorizer(analyzer='char')
x = v.fit_transform(df['cipher'])
len(v.get_feature_names())

27

In [23]:
v = TfidfVectorizer(analyzer='char')
x_ss = v.fit_transform(ss_train['cipher'])

v = TfidfVectorizer(analyzer='char')
x_vig = v.fit_transform(vig_train['cipher'])

In [7]:
from sklearn.svm import SVC
clf = SVC(probability=True)
clf.fit(x, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [24]:
from sklearn.svm import SVC
clf_ss = SVC()
clf_ss.fit(x_ss, y_ss)
clf_vig = SVC()
clf_vig.fit(x_vig, y_vig)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

# Test Data Preprocessing

In [8]:
# import docx
# doc = docx.Document("dataset_cryptosystem.docx")

# text = []
# for p in doc.paragraphs:
#     text.append(p.text)
    
# len(text)

# d = [0,1,2,3,4,5,6,7,8,9,10,11, 12, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 34, 35, 36, 38]
# d = sorted(d, reverse=True)
# for i in d:
#     del text[i]

test = pd.read_csv("test.csv", header=None, names=["cipher"])

y_test = [1]*10 + [0]*10

x_test = v.fit_transform(test['cipher'])

# test.to_csv("test.csv", index_label=False, header=False)

# Prediction

In [9]:
clf.predict(x_test)

array([1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1])

In [25]:
ss_pred = clf_ss.predict(x_test)
vig_pred = clf_vig.predict(x_test)

In [17]:
import numpy as np
ss_pred = np.array(ss_pred)
vig_pred = np.array(vig_pred)
pred = np.logical_xor(ss_pred, vig_pred)
pred

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [27]:
ss_pred

array([1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1])